// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/jrswab/go-htmx-forge/views/layout"

func Show() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p class=\"text-center\"></p><p class=\"text-center mt-6\"></p><div id=\"webapp-alert\" class=\"relative mt-6 mb-4 p-4 bg-gray-200 text-gray-900 border rounded border-gray-500\" role=\"alert\"><p style=\"font-size: 1.2rem\"><b>👋 Hey, this is a progressive web app!</b></p><p>This means you can \"install\" it to your device and use it just like any other app.</p><p id=\"webapp-install-text\">To add this app to your home screen look for \"Install App\", \"Add to Home Screen\", or something similar, in your browser options.</p></div><script type=\"text/javascript\" src=\"/static/get_useragent.js\"></script> <script type=\"text/javascript\">\n            document.addEventListener(\"DOMContentLoaded\", function() {\n                // Add the device-specific class to the body element\n                const deviceType = getDeviceType();\n                document.body.classList.add(deviceType);\n\n                // Set device-specific instructions\n                const instructions = document.getElementById(\"webapp-install-text\");\n\n                if (deviceType === \"ios\") {\n                    instructions.textContent = \"To add this app to your home screen, tap the share icon and select 'Add to Home Screen'.\";\n                }\n                \n                if (deviceType === \"android\") {\n                    instructions.textContent = \"To add this app to your home screen, tap your browser's menu icon and select 'Install The Site...'\";\n                } \n            });\n        </script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base("Welcome to the Site").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
